# Generated by Django 3.2 on 2023-05-07 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ExpenseModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_expense', models.IntegerField(verbose_name='総支出')),
                ('fixed_cost', models.IntegerField(verbose_name='固定費')),
                ('variable_cost', models.IntegerField(verbose_name='変動費')),
            ],
        ),
        migrations.CreateModel(
            name='IncomeModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('income', models.IntegerField(verbose_name='総収入')),
                ('income_date', models.DateField()),
                ('salary', models.IntegerField(verbose_name='給料')),
                ('commuting_allowance', models.IntegerField(verbose_name='交通費')),
                ('total_tax', models.IntegerField(verbose_name='税金/社会保険料')),
            ],
        ),
        migrations.CreateModel(
            name='TaxModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_tax', models.IntegerField(verbose_name='税金/社会保険料')),
                ('tax_date', models.DateField()),
                ('category', models.CharField(choices=[('health_insurance', '健康保険'), ('welfare_pension', '厚生年金'), ('employment_insurance', '雇用保険'), ('income_tax', '所得税'), ('resident_tax', '住民税')], max_length=100)),
                ('health_insurance', models.IntegerField(verbose_name='健康保険')),
                ('welfare_pension', models.IntegerField(verbose_name='厚生年金')),
                ('employment_insurance', models.IntegerField(verbose_name='雇用保険')),
                ('income_tax', models.IntegerField(verbose_name='所得税')),
                ('resident_tax', models.IntegerField(verbose_name='住民税')),
            ],
        ),
    ]
