# Generated by Django 3.2 on 2023-05-07 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kakeiboapp', '0002_auto_20230507_1001'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incomemodel',
            name='income',
            field=models.IntegerField(blank=True, default=0, verbose_name='総収入'),
        ),
        migrations.AlterField(
            model_name='taxmodel',
            name='employment_insurance',
            field=models.IntegerField(blank=True, default=0, verbose_name='雇用保険'),
        ),
        migrations.AlterField(
            model_name='taxmodel',
            name='health_insurance',
            field=models.IntegerField(blank=True, default=0, verbose_name='健康保険'),
        ),
        migrations.AlterField(
            model_name='taxmodel',
            name='income_tax',
            field=models.IntegerField(blank=True, default=0, verbose_name='所得税'),
        ),
        migrations.AlterField(
            model_name='taxmodel',
            name='resident_tax',
            field=models.IntegerField(blank=True, default=0, verbose_name='住民税'),
        ),
        migrations.AlterField(
            model_name='taxmodel',
            name='total_tax',
            field=models.IntegerField(blank=True, default=0, verbose_name='税金/社会保険料'),
        ),
        migrations.AlterField(
            model_name='taxmodel',
            name='welfare_pension',
            field=models.IntegerField(blank=True, default=0, verbose_name='厚生年金'),
        ),
    ]
