# Generated by Django 3.2 on 2023-05-11 07:18

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('kakeiboapp', '0004_remove_taxmodel_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incomemodel',
            name='income_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
