# Generated by Django 3.2 on 2023-05-11 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kakeiboapp', '0005_alter_incomemodel_income_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incomemodel',
            name='income_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
