# Generated by Django 3.2 on 2023-05-12 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kakeiboapp', '0007_auto_20230512_0914'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incomemodel',
            name='fixed_cost',
            field=models.IntegerField(blank=True, default=0, verbose_name='固定費'),
        ),
        migrations.AlterField(
            model_name='incomemodel',
            name='total_expense',
            field=models.IntegerField(blank=True, default=0, verbose_name='総支出'),
        ),
        migrations.AlterField(
            model_name='incomemodel',
            name='variable_cost',
            field=models.IntegerField(blank=True, default=0, verbose_name='変動費'),
        ),
    ]
