# Generated by Django 3.2 on 2023-05-12 12:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kakeiboapp', '0009_auto_20230512_1123'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='IncomeModel',
            new_name='MonthModel',
        ),
    ]
